// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Zavrsni.Models
{
    [Table("Admin")]
    public partial class Admin
    {
        [Key]
        public int AdminID { get; set; }
        [Required]
        [StringLength(50)]
        public string Role { get; set; }

        [ForeignKey("AdminID")]
        [InverseProperty("Admin")]
        public virtual User AdminNavigation { get; set; }
    }
}