// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Zavrsni.Models
{
    public partial class Course
    {
        public Course()
        {
            Purchases = new HashSet<Purchase>();
        }

        [Key]
        public int CourseID { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public int TeacherID { get; set; }
        [Required]
        [StringLength(100)]
        public string Description { get; set; }
        public int Duration { get; set; }
        public int Price { get; set; }

        [ForeignKey("TeacherID")]
        [InverseProperty("Courses")]
        public virtual Teacher Teacher { get; set; }
        [InverseProperty("Course")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}