// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Zavrsni.Models;

namespace Zavrsni.Models
{
    public partial interface IZavrsniRadBizUpContextProcedures
    {
    }
}
