// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Zavrsni.Models
{
    public partial class Purchase
    {
        [Key]
        public int StudentID { get; set; }
        [Key]
        public int CourseID { get; set; }

        [ForeignKey("CourseID")]
        [InverseProperty("Purchases")]
        public virtual Course Course { get; set; }
        [ForeignKey("StudentID")]
        [InverseProperty("Purchases")]
        public virtual Student Student { get; set; }
    }
}