// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Zavrsni.Models
{
    public partial class Student
    {
        public Student()
        {
            Purchases = new HashSet<Purchase>();
        }

        [Key]
        public int StudentID { get; set; }
        [Required]
        [StringLength(50)]
        public string CardName { get; set; }
        [Required]
        [StringLength(50)]
        public string CardNumber { get; set; }
        [Required]
        [StringLength(50)]
        public string ExpirationDate { get; set; }
        [Required]
        [StringLength(50)]
        public string CSV { get; set; }
        
        [StringLength(7)]
        public string Role { get; set; }

        [ForeignKey("StudentID")]
        [InverseProperty("Student")]
        public virtual User StudentNavigation { get; set; }
        [InverseProperty("Student")]
        public virtual ICollection<Purchase> Purchases { get; set; }
    }
}