// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Zavrsni.Models
{
    public partial class Teacher
    {
        public Teacher()
        {
            Courses = new HashSet<Course>();
        }

        [Key]
        public int TeacherID { get; set; }
        [Required]
        [StringLength(100)]
        public string Introduction { get; set; }
        [Required]
        [StringLength(50)]
        public string Role { get; set; }
        public int? NumCoursesCreated { get; set; }

        [ForeignKey("TeacherID")]
        [InverseProperty("Teacher")]
        public virtual User TeacherNavigation { get; set; }
        [InverseProperty("Teacher")]
        public virtual ICollection<Course> Courses { get; set; }
    }
}