// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using Zavrsni.Models;

namespace Zavrsni.Models
{
    public partial class ZavrsniRadBizUpContext
    {

        [DbFunction("GetNumCoursesCreated", "dbo")]
        public static int? GetNumCoursesCreated(int? TeacherID)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
