// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using Zavrsni.Models;

namespace Zavrsni.Models
{
    public partial class ZavrsniRadBizUpContext
    {
        private IZavrsniRadBizUpContextProcedures _procedures;

        public virtual IZavrsniRadBizUpContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new ZavrsniRadBizUpContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IZavrsniRadBizUpContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
        }
    }

    public partial class ZavrsniRadBizUpContextProcedures : IZavrsniRadBizUpContextProcedures
    {
        private readonly ZavrsniRadBizUpContext _context;

        public ZavrsniRadBizUpContextProcedures(ZavrsniRadBizUpContext context)
        {
            _context = context;
        }
    }
}
